# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "laanayabdrzak.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Abderrazak LAANAYA
  avatar: ic_profil.jpg
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Gather every day to share and discuss the best dev tools & open source projects that helps us stay productive</p>

  header_text_feature_image:
  footer_text: >
   Powered by laanayabdrzak

  # Icons
  rss: false
  email_address: "laanayabdrzak@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "abderrazak.laanaya"
  flickr:
  github: "laanayabdrzak"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/laanayabdrzak"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "More ..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Roboto:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
